[package]
name = "rust_pyxeled_py"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_pyxeled"
crate-type = ["cdylib"]

[dependencies]
rust_pyxeled = { path = "../rust_pyxeled" }
pyo3 = { version = "0.21", features = ["extension-module", "abi3-py39"] }
image = "0.24"

